# Generated by Django 5.2.6 on 2025-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/", verbose_name="Image"
            ),
        ),
    ]
