# Generated by Django 5.2.6 on 2025-09-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("subtitle", models.TextField(verbose_name="Subtitle")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hero/",
                        verbose_name="Background Image",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
    ]
